version: 2.1

orbs:
    aws-cli: circleci/aws-cli@3.1.5
    #kubernetes: circleci/kubernetes@1.3

jobs:
    install_lint:
        docker:
            - image: python:3.7.3-stretch
            
        working_directory: ~/repo
        
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "requirements.txt" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-
            - run:
                name: "Install py dependencies and hadolint"
                command: |
                
                    # REMOVE LATER #######
                    # python3 -m venv ~/.project
                    # . ~/.project/bin/activate
                    
                    # Configuring python virtual environment
                    python3 -m venv venv
                    . venv/bin/activate
                    
                    # Installing python dependencies and hadolint
                    make install
                    
            - save_cache:
                paths:
                    - ./venv
                key: v1-dependencies-{{ checksum "requirements.txt" }}
                
            - run:
                name: "Lint python app and Docker file"
                command: |
                    . venv/bin/activate
                    make lint
    
    build_publish_dockerimage:
        docker:
            - image: cimg/base:stable
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: "Create docker image"
                command: |
                    bash scripts/docker_build.sh
            - run:
                name: "Upload docker image to docker hub"
                command: bash scripts/docker_publish.sh $DOCKERHUB_PW
            